name: Report an issue with registry.k8s.io
description: Report a bug encountered while using registry.k8s.io
labels: ["sig/k8s-infra", "kind/bug", "needs/triage"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: what-expected
    attributes:
      label: Expectation
      description: what did you expect to happen?
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Debugging Information
      description: >-
        Bugs **MUST** include debugging logs from general steps in https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will provide more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kubernetes/community/blob/master/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true